### ISSUE TITLE
[1.19.2] Can click through Polymorph menu.

### ISSUE THREAD

**Issue by Sandriell** [62832/RefinedPolymorphism#1]
First off, thanks for making this mod to add interaction between Polymorph and Refined Storage.

The issue I am experiencing (and this may be something on Polymorph's end) is when clicking on the desired item to craft in the popup menu for Polymorph, it will click through the menu and pick up something from the refined storage inventory.

Can see in the screenshot how the item in my refined storage inventory is highlighted behind the menu, and when clicking, it will pick up that item.

![2023-11-26_17 35 33](https://github.com/62832/RefinedPolymorphism/assets/10704907/0d8b72f4-f1df-477a-8b35-f9115e2db8f6)

It still works to change the crafting result, just annoying having it pick up the item too.

refinedstorage-1.11.7
refinedpolymorph-0.1.0-1.19.2
polymorph-forge-0.46.5+1.19.2
Forge: 43.2.21

**Comment by 62832** [comment]
I'm not sure there's anything I can personally do about this, and seeing that this also happens with the AE2 version of this add-on it may well be on Polymorph's end.

**Comment by TheIllusiveC4** [comment]
This should be fixed now in the latest Polymorph update, 0.46.6+1.19.2.
