### ISSUE TITLE
Solution for button shifting incorrectly on screen resize

### ISSUE THREAD

**Issue by TheIllusiveC4** [62832/RefinedPolymorphism#2]
I recently released an update for Polymorph on 1.18.x which still had its own AE2 and RS integration and I had a chance to look into the issue with the button shifting incorrectly when the screen or GUI was resized. This is the commit:
https://github.com/illusivesoulworks/polymorph/commit/2d8be1036abf93c30c98ad2c09156cfdbc98826b

I believe something similar, if not exactly the same, could be used to solve this same issue on these add-ons. It essentially involves checking for changes in height and then refreshing both the output slot and widgets accordingly.

**Comment by 62832** [comment]
Sounds great. I'll throw these in when I get the chance.
